# Generated by Django 2.2.8 on 2020-01-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_post',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
