# Generated by Django 2.2.8 on 2020-01-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0002_project_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='rate',
            new_name='design',
        ),
    ]
