# Generated by Django 2.2.8 on 2020-01-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0003_auto_20200111_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='content',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rates',
            name='usability',
            field=models.IntegerField(default=0),
        ),
    ]
