# Generated by Django 2.2.8 on 2020-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_app', '0004_auto_20200111_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='content',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rates',
            name='design',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rates',
            name='usability',
            field=models.IntegerField(default=1),
        ),
    ]
